#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
# load scripting addition
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# focus the hoverd windows
yabai -m config focus_follows_mouse          off

#External Bar
yabai -m config external_bar all:24:0

# turn off some stuff
yabai -m config mouse_follows_focus          off
yabai -m config window_shadow                off
yabai -m config auto_balance                 off

# devide windows by 2 by default
yabai -m config split_ratio                  0.50

# window border
yabai -m config window_border                off
yabai -m config window_border_width          5
yabai -m config active_window_border_color   0xFF6faec0
yabai -m config normal_window_border_color   0xFF3e4050
yabai -m config insert_feedback_color        0xffd75f5f

# window opacity (leave it default)
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90

# mouse stuff
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# global settings
yabai -m config window_origin_display        default
yabai -m config window_placement             second_child
yabai -m config window_topmost               off

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  12
yabai -m config bottom_padding               12
yabai -m config left_padding                 12
yabai -m config right_padding                12
yabai -m config window_gap                   12


# float system preferences. Most of these just diable Yabai form resizing them.
yabai -m rule --add app="^System Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="^Karabiner-Elements$" sticky=on layer=above manage=off
yabai -m rule --add app="^Karabiner-EventViewer$" sticky=on layer=above manage=off
yabai -m rule --add app="^Finder$" sticky=on layer=above manage=off
yabai -m rule --add app="^Keka$" sticky=on layer=above manage=off
yabai -m rule --add app="^Alfred Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="^Disk Utility$" sticky=on layer=above manage=off
yabai -m rule --add app="^System Information$" sticky=on layer=above manage=off
yabai -m rule --add app="^Activity Monitor$" sticky=on layer=above manage=off
yabai -m rule --add app="^Path Finder$" manage=off
yabai -m rule --add app="^TeamViewer$" sticky=off layer=above manage=off
yabai -m rule --add app="Fantastical" manage=off
yabai -m rule --add app="^Spotify$" manage=off
yabai -m rule --add app="^Flux$" manage=off
yabai -m rule --add app="^Time Out$" manage=off
yabai -m rule --add app="^perl_client_app$" manage=off
yabai -m rule --add app="^console$" manage=off
yabai -m rule --add app="^Harvest$" manage=off
yabai -m rule --add app="^CiscoSparkHelper$" manage=off
yabai -m rule --add app="^Logi Options$" manage=off
yabai -m rule --add app="^Cisco Webex Start$" manage=off
yabai -m rule --add app="^Private Internet Access$" manage=off
yabai -m rule --add app="^Raycast$" manage=off
yabai -m rule --add app="^Focus To-Do$" manage=off
yabai -m rule --add app="^JetBrains Toolbox$" manage=off
yabai -m rule --add app="^Telegram$" sticky=on layer=above manage=off
yabai -m rule --add app="^Photo Booth$" sticky=on layer=above manage=off
yabai -m rule --add app="^MenubarX$" sticky=on layer=above manage=off
yabai -m rule --add app="^MonitorControl$" sticky=on layer=above manage=off
yabai -m rule --add app="^Android Studio$" sticky=on layer=above manage=off
yabai -m rule --add app="^GoLand$" sticky=on layer=above manage=off
yabai -m rule --add app="^DataGrip$" sticky=on layer=above manage=off
yabai -m rule --add app="^Docker Desktop$" sticky=on layer=above manage=off
yabai -m rule --add app="^Spark$" sticky=on layer=above manage=off
yabai -m rule --add app="^Font Book$" sticky=on layer=above manage=off
yabai -m rule --add app="^Preview$" sticky=on layer=above manage=off
yabai -m rule --add app="^IINA$" sticky=on layer=above manage=off
yabai -m rule --add app="^VLC$" sticky=on layer=above manage=off
yabai -m rule --add app="^WhatsApp$" sticky=on layer=above manage=off
yabai -m rule --add app="^App Store$" sticky=on layer=above manage=off
yabai -m rule --add app="^TickTick$" sticky=on layer=above manage=off
yabai -m rule --add app="^Books$" sticky=on layer=above manage=off




# add the following to the end of your yabairc to have it launch automatically when yabai starts.
# make sure the limelight binary is added somewhere in your $PATH

# kill any existing limelight process if one exists, before we launch a new one
# killall limelight &> /dev/null
# limelight &> /dev/null &

  # S K E T C H Y B A R  E V E N T S
yabai -m signal --add event=window_focused action="sketchybar -m --trigger window_focus &> /dev/null"
yabai -m signal --add event=window_title_changed action="sketchybar -m --trigger title_change &> /dev/null"

echo "yabai configuration loaded.."
