#!/usr/bin/env sh

limelight -m config width 3
limelight -m config radius 0
limelight -m config placement exterior
limelight -m config active_color 0xFF94e2d5
limelight -m config normal_color 0x00FFFFFF

echo "limelight configuration loaded.."

