#!/usr/bin/env sh

limelight -m config width 3
limelight -m config radius 0
limelight -m config placement exterior
limelight -m config active_color 0xfff5e0dc
limelight -m config normal_color 0xff585b70

echo "limelight configuration loaded.."
