#!/usr/bin/env sh

limelight -m config width 3
limelight -m config radius 10
limelight -m config placement exterior
limelight -m config active_color 0xffb4befe
limelight -m config normal_color 0xff4547a

echo "limelight configuration loaded.."
