#!/usr/bin/env bash

sketchybar -m --add item           space_template left                                   \
              --set space_template drawing=off                                           \
                                   label.drawing=off                                     \
                                   icon.padding_left=5                                   \
                                   icon.padding_right=5                                  \
                                   icon.highlight_color=0xfffe8019                       \
                                   click_script="yabai -m space --focus \$(echo \$NAME | tr '.' ' ' | awk '{ print \$2 }')" \
              --add item           updater left                                          \
              --set updater        script="~/.config/sketchybar/plugins/space_update.sh" \
                                   drawing=off                                           \
                                   updates=on                                            \
              --subscribe          updater space_change display_change

args=()
for i in {1..10}; do
  args+=(--clone space.${i} space_template \
         --set   space.${i} icon=${i})
done 
sketchybar -m "${args[@]}" --update
