#!/usr/bin/env sh

source "$HOME/.config/sketchybar/colors.sh" # loads all defined colors
source "$HOME/.config/sketchybar/icons.sh" # loads all defined icons

ITEM_DIR="$HOME/.config/sketchybar/items" # Directory where the items are configured
PLUGIN_DIR="$HOME/.config/sketchybar/plugins" # Directory where all the plugin scripts are stored

FONT="SF Pro"
SPACE_CLICK_SCRIPT="yabai -m space --focus \$SID 2>/dev/null" # The script that is run for clicking on space components

POPUP_BORDER_WIDTH=2
POPUP_CORNER_RADIUS=11

PADDINGS=4
BARPADDINGS=10

SHADOW=on

# Setting up the general bar appearance and default values
sketchybar --bar     height=24                                         \
                     color=$BAR_COLOR                                  \
                     shadow=$SHADOW                                    \
                     position=top                                      \
                     sticky=on                                         \
                     padding_right=$BARPADDINGS                        \
                     padding_left=$BARPADDINGS                         \
                     blur_radius=20                                    \
                     notch_width=0                                     \
                                                                       \
           --default updates=when_shown                                \
                     icon.font="$FONT:Bold:14.0"                       \
                     icon.color=$ICON_COLOR                            \
                     icon.padding_left=$PADDINGS                       \
                     icon.padding_right=$PADDINGS                      \
                     label.font="$FONT:Semibold:13.0"                  \
                     label.color=$LABEL_COLOR                          \
                     label.padding_left=$PADDINGS                      \
                     label.padding_right=$PADDINGS                     \
                     popup.background.border_width=2                   \
                     popup.background.corner_radius=11                 \
                     popup.background.border_color=$POPUP_BORDER_COLOR \
                     popup.background.color=$POPUP_BACKGROUND_COLOR    \
                     popup.background.shadow.drawing=$SHADOW


#Left
source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/front_app.sh"
# source "$ITEM_DIR/window_title.sh"

#Middle
source "$ITEM_DIR/spotify.sh"

#Right
source "$ITEM_DIR/clock.sh"
source "$ITEM_DIR/battery.sh"

############################ FINALIZING THE SETUP ########################
sketchybar --update

echo "sketchybar configuration loaded.."
